### ISSUE TITLE
Create the frontend app base structure using create react app

### ISSUE THREAD

**Issue by comoser** [reach4help/covidaid#17]
Assumptions:
- TypeScript based
- ESlint configured
- Husky pre-commit hook to lint
- Configured tor nice development env with TypeScript

**Comment by comoser** [comment]
Actually still missing from this PR:

I would like to insert conventional commits in the future commits that we have, so in order to do that I would like to add:
- `commitlint.config.js` file

@s0 I have a question for you. Since I don't have husky configured in the main `package.json` of the repo, when I commit, it totally ignores the git hook, how can we get around this?

**Comment by s0** [comment]
We can actually have packages installed at the root of the project, and commands specified in the root of the project too!

**Comment by comoser** [comment]
Also, on this issue we will enforce `conventional-commits` from now on, on the whole monorepo

**Comment by comoser** [comment]
Pull request with docs updates worth mentioning: https://github.com/reach4help/covidaid/pull/37
